spring.application.name=ExpenseTracker

# MongoDB Connection Property
# PLEASE REPLACE THE VALUE BELOW WITH YOUR ACTUAL MONGODB ATLAS CONNECTION STRING
spring.data.mongodb.uri=mongodb+srv://vibecoding360_db_user:Kalel%40123@expense-tracker.o3hkity.mongodb.net/expense_tracker?appName=expense-tracker

# Web Server Port
server.port=5000
